---
title: "VAF distribution plots"
author: "Natalia Brzozowska"
date: "2023-10-26"
output: html_document
---

```{r}
library(dplyr)
library(cowplot)
library(dndscv)
library(tidyverse)
library(seqinr)
library(data.table)
```

```{r setup, include=FALSE}
homedir <- "/lustre/scratch126/casm/team154pc/nb15/liver/"

exome_samples <- c("PD60232","PD60233","PD60802","PD60803")

refCDSpath <- "data/reference_files/refcds_GRCh38-GencodeV18+Appris.rda"
load(refCDSpath)

wgs_calls <- fread("data/calls/wgs_calls.csv", sep = ",") %>%
  dplyr::rename(chr = Chrom,
                pos = Pos,
                ref = Ref,
                mut = Alt) %>%
  dplyr::select(sampleID,chr,pos,ref,mut,mut_id,coverage,Mut_Frags,vaf,Project) %>%
  filter(coverage > 10,
         chr %in% paste0("chr", 1:22))

exome_calls <- fread("data/calls/exome_calls.csv", sep = ",") %>%
  dplyr::rename(chr = Chrom,
                pos = Pos,
                ref = Ref,
                mut = Alt) %>%
  dplyr::select(sampleID,chr,pos,ref,mut,mut_id,coverage,Mut_Frags,vaf,Project) %>%
  filter(coverage > 10,
         chr %in% paste0("chr", 1:22))

all_calls <- rbind(exome_calls, wgs_calls)

annotmuts <- fread("outputs/A1AD_dndsout_annotmuts.tsv", sep="\t")

```

```{r}
# Covert genomic bp to coding sequence coordinate 
getCDSindex <- function(intervals) {
  strand <- intervals$strand[1]
  allBP <- tibble()
  for(exon in 1:length(intervals$length)) {
    exonBP <- tibble(pos = seq(intervals$start[exon], intervals$end[exon]))
    allBP <- bind_rows(allBP, exonBP) 
  }
  # Forward strand standard
  if(strand == 1) {
  allBP <- allBP |> 
      mutate(cdsPos = seq(1:sum(intervals$length)))    
  } else {
    #Reverse strand flip cds coords so all genes show left to right
    allBP <- allBP |> 
      mutate(cdsPos = seq(from = sum(intervals$length), to = 1))  
  }
  return(allBP)
}

# Function to get the affected amino acid for indel mutations
getAminoAcidForIndel <- Vectorize(function(impact, cdsPos, name, ref, alt) {
    codon_number <- ceiling(cdsPos / 3)
    codon_start <- codon_number * 3 - 2
    codon_end <- codon_start + 2
    ref_codon <- tolower(as.character(substr(g_CDS$seq_cds, codon_start, codon_end)))
    ref_aa <- seqinr::translate(s2c(ref_codon), sens = "F")
    if (name == "mnv") {
        mut_codon <- gsub(ref, tolower(alt), ref_codon, ignore.case = TRUE)
        mut_aa <- seqinr::translate(s2c(mut_codon), sens = "F")
        return(paste0(ref_aa, codon_number, mut_aa))
    }  
    if (impact == "Indel") {
        return(paste0(ref_aa, codon_number, name)) 
    } else if (name != "mnv" & impact != "Indel") {
        return(name)
    }
})
```

```{r}

genes <- as.data.frame(matrix(nrow=length(RefCDS), ncol=2))
colnames(genes) <- c("gene_name","row_in_refcds")
for( i in 1:length(RefCDS)){
  genes$gene_name[i] <- RefCDS[[i]]$gene_name
  genes$row_in_refcds[i] <- i
}

g_CDS <- RefCDS[[which(genes$gene_name=="SERPINA1")]]
intervals_cds0 <- tibble(chr = g_CDS$chr,
                        strand = g_CDS$strand,
                        start = g_CDS$intervals_cds[,1],
                        end = g_CDS$intervals_cds[,2]) |> 
  arrange(start) |> 
  mutate(length = (end + 1) - start) 

cdsCoordsIndex <- getCDSindex(intervals_cds0)

SERPINA1_annotmuts <- annotmuts[annotmuts$gene == "SERPINA1",] |>
    left_join(cdsCoordsIndex, by="pos")  |>
    mutate(impact = replace_na(impact, "Non-coding")) |> 
    mutate(impact = str_replace(impact, "no-SNV", "Indel"))  |> 
    mutate(name = if_else(impact == "Indel", 
                        #Formating for indels
                        replace_na(str_remove(ntchange, ".*-"), ".") |> 
                          str_replace("frshift", "FS") |> 
                          str_replace("inframe", "IF"), 
                        #Name for SNVs
                        replace_na(aachange, "."))) |>
    mutate(name = getAminoAcidForIndel(impact, cdsPos, name, ref, mut))
```

```{r}
#Annotate mutations

combined_muts_annot <- left_join(x = all_calls |> 
                                   mutate(chr=gsub("chr","",chr)), 
                                 y = SERPINA1_annotmuts |>
                                     select(-sampleID) |>
                                     distinct(), 
                         by = c("chr","pos","ref","mut")) 

SERPINA1 <- combined_muts_annot |>
  filter(gene == "SERPINA1") |>
  arrange(aachange) |>
  mutate(chr=as.integer(chr)) |>
  group_by(name) |>
  slice_max(order_by = vaf, n = 1, with_ties = FALSE)

SERPINA1 <- as.data.frame(SERPINA1)
SERPINA1 <- SERPINA1[complete.cases(SERPINA1), ]

head(SERPINA1)
```

```{r}
plot_list <- list()

for(i in seq_len(nrow(SERPINA1))){
  sampleID <- as.character(SERPINA1[i, "sampleID"])
  mutation <- SERPINA1[i,]
  
  sample_calls <- all_calls %>% filter(sampleID == !!sampleID)

  if(unique(sample_calls$Project) %in% c(3131,2814)){
    seq <- "WES"
  }else if(unique(sample_calls$Project) == 2792){
    seq <- "WGS"
  }
  
  p <- ggplot(sample_calls, aes(x=vaf)) +
  geom_density(fill="#368B9E",alpha=0.4) + 
    geom_vline(data=mutation, aes(xintercept=vaf),
             linetype="dashed", color="#368B9E",linewidth = 0.5) +
  theme_minimal() +
  labs(title=sampleID, subtitle=seq,x="VAF", y = "") + 
  xlim(0,1) +
  #labs(title="", x="VAF", y = "") + 
  annotate("text", x = mutation$vaf+0.02, y = 0.04, label = paste(SERPINA1[i, "name"]), vjust = -0.5, hjust = 0, color="#368B9E",size=3) +
  theme(plot.title = element_text(size = 10),
        plot.subtitle = element_text(size = 8),
        axis.title.x = element_text(size = 8))
  
  print(p)
  
  plot_list[[i]] <- p 
}

grid <- plot_grid(plotlist=plot_list,nrow=7)
ggsave("outputs/VAF_density_plots_filtered.pdf", grid, width = 8.27, height = 11.69, units = "in")

```

#VAF histograms like in endometrium paper

```{r}
library(tidyr)
library(purrr)
library(moments)
library(hrbrthemes)
library(viridis)
library(ggridges)

# Generate a unique list of donor IDs
donors <- unique(substr(wgs_calls$sampleID, 1, 7))

# Initialize an empty data frame to store data for all donors
all_donors_data <- data.frame()

# Loop over each donor
for (donorID in donors) {
  
  # Filter data for the current donor
  donor_calls <- wgs_calls %>%
    filter(grepl(donorID, sampleID))
  
  # Calculate median for each sampleID
  median_data <- donor_calls %>%
    dplyr::group_by(sampleID) %>%
    dplyr::summarize(median = median(vaf)) %>%
    arrange(median)
  
  # Reorder sampleID based on median and reverse the order
  donor_calls$sampleID <- factor(donor_calls$sampleID, levels = rev(median_data$sampleID))
  
  # Add the donor ID as a column
  donor_calls$donorID <- donorID
  
  # Combine the data into a single data frame
  all_donors_data <- bind_rows(all_donors_data, donor_calls)
}

# Calculate the number of samples for each donor
donor_sample_counts <- all_donors_data %>%
  dplyr::group_by(donorID) %>%
  dplyr::summarise(n_samples = n_distinct(sampleID))

# Create custom labels for facet_wrap
all_donors_data <- all_donors_data %>%
  dplyr::left_join(donor_sample_counts, by = "donorID") %>%
  mutate(donor_label = paste0(donorID, " (n = ", n_samples, ")"))

# Generate a color palette for donors
donor_colors <- viridis(length(donors))

# Create the plot with facet_wrap to show each donor in a separate facet
vaf_plot <- ggplot(all_donors_data, aes(x=vaf, y=sampleID, fill=donorID, group=sampleID)) +
  geom_density_ridges(scale = 20, alpha=1) +
  scale_fill_manual(values=donor_colors) +
  facet_wrap(~ donor_label, scales = "free_y") +  # Use custom labels with sample counts
  theme_minimal() +
  geom_vline(xintercept = c(0.25, 0.75), linetype = "dashed", color = "black") +
  scale_x_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.00)) +
  theme(
    legend.position = "none", 
    axis.text.y = element_blank(),  # Remove sampleID labels
    axis.ticks.y = element_blank()  # Optionally remove y-axis ticks as well
  ) +
  labs(x = "VAF", y = NULL) 
  
ggsave("outputs/vaf_multi_density_plots_wgs.pdf", plot = vaf_plot)
      
```

# plot the same for exomes
```{r}
donors <- unique(substr(exome_calls$sampleID, 1, 7))

# Initialize an empty data frame to store data for all donors
all_donors_data <- data.frame()

# Loop over each donor
for (donorID in donors) {
  
  # Filter data for the current donor
  donor_calls <- exome_calls %>%
    filter(grepl(donorID, sampleID))
  
  # Calculate median for each sampleID
  median_data <- donor_calls %>%
    dplyr::group_by(sampleID) %>%
    dplyr::summarize(median = median(vaf)) %>%
    arrange(median)
  
  # Reorder sampleID based on median and reverse the order
  donor_calls$sampleID <- factor(donor_calls$sampleID, levels = rev(median_data$sampleID))
  
  # Add the donor ID as a column
  donor_calls$donorID <- donorID
  
  # Combine the data into a single data frame
  all_donors_data <- bind_rows(all_donors_data, donor_calls)
}

# Calculate the number of samples for each donor
donor_sample_counts <- all_donors_data %>%
  dplyr::group_by(donorID) %>%
  dplyr::summarise(n_samples = n_distinct(sampleID))

# Create custom labels for facet_wrap
all_donors_data <- all_donors_data %>%
  dplyr::left_join(donor_sample_counts, by = "donorID") %>%
  mutate(donor_label = paste0(donorID, " (n = ", n_samples, ")"))

# Generate a color palette for donors
donor_colors <- viridis(length(donors))

# Create the plot with facet_wrap to show each donor in a separate facet
exome_vaf_plot <- ggplot(all_donors_data, aes(x=vaf, y=sampleID, fill=donorID, group=sampleID)) +
  geom_density_ridges(scale = 20, alpha=1) +
  scale_fill_manual(values=donor_colors) +
  facet_wrap(~ donor_label, scales = "free_y") +  # Use custom labels with sample counts
  theme_minimal() +
  geom_vline(xintercept = c(0.25, 0.75), linetype = "dashed", color = "black") +
  scale_x_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.00)) +
  theme(
    legend.position = "none", 
    axis.text.y = element_blank(),  # Remove sampleID labels
    axis.ticks.y = element_blank()  # Optionally remove y-axis ticks as well
  ) +
  labs(x = "VAF", y = NULL) 
  
ggsave("outputs/vaf_multi_density_plots_exome.pdf", plot = exome_vaf_plot)


```